### ISSUE TITLE
Add context based issue view

### ISSUE THREAD

**Issue by kwave** [hmvictor/radar-netbeans#38]
It would be great to be able to only view issues that relate to the currently opened source-file. Maybe also display issues as sidebar hint directly in the Sourcecode file.

**Comment by hmvictor** [comment]
It seems a useful idea. Let me analyze this request.

**Comment by arvidvillen** [comment]
I would love to see issues directly in the source-file (like [jsHint]( https://github.com/luka-zitnik/jshint-for-netbeans)). The project I’m working on has thousands of issues and its almost impossible to track the ones my team are responsible for. 
And yes, I know, we need split the project up :)

**Comment by hmvictor** [comment]
Hi @kwave , @arvidvillen Radar 2.6 (still in progress) has now support for editor annotations so if the file is open after Retrieving the issues you can see them in the code.

**Comment by arvidvillen** [comment]
Love it :)
