### ISSUE TITLE
Radar is not compatible with official SonarQube 5.3

### ISSUE THREAD

**Issue by dannnnn** [hmvictor/radar-netbeans#41]
Since Sonar released official 5.3 version, plugin seems not to be compatible, although it is compatible with official version 5.2

**Comment by hmvictor** [comment]
Hi, version 2.5 tonight was released (http://plugins.netbeans.org/plugin/51532/radar-netbeans) and includes fixes for SonarQube 5.3.

**Comment by dannnnn** [comment]
Thanks for fast fix, we will test it
