### ISSUE TITLE
Add a quick filter in Project Chooser dialog

### ISSUE THREAD

**Issue by Gittino** [hmvictor/radar-netbeans#42]
Hi, could you kindly add a quick filter in the project chooser dialog that appears when "Get issues from server.." is selected?
In my company there is a huge amount of projects (the sonar dashboard via browser reports 2,763 results) and it is almost impossible to select the correct one simply scrolling the dropdown menu. 
It is sufficient a field where to write a part of the name to have a filtering of the jdialog entries.
Thanks and best regards,

**Comment by hmvictor** [comment]
Hi @Gittino , the implementation of this request is in Branch 2.6.

Thank you for your feedback.

**Comment by Gittino** [comment]
Thanks a lot!
