### ISSUE TITLE
Error when opening issues when source directory is outside of nbproject

### ISSUE THREAD

**Issue by apannwitz** [hmvictor/radar-netbeans#49]
Hi,

when I click on an issue to open the sourcefile, the file will not be found, because of a wrong path.

My project path is e.g. "C:\Users\xxx\project.netbeans\nbproject"
My source path is e.g. "C:\Users\xxx\project\wwwroot"

A click on issues tries to open: "C:\Users\xxx\project.netbeans\wwwroot\test.php" which is wrong, because it must be "C:\Users\xxx\project\wwwroot\test.php" (without .netbeans)

BTW: My "Source Folder" is well configured in Netbeans.

**Comment by hmvictor** [comment]
Hi, @apannwitz Are you using Get Issues from Server or Get Issues with Sonar Runner?

Thanks.

**Comment by hmvictor** [comment]
Hi again @apannwitz.

Could you attach an example of a project to reproduce this bug?

Thank you.
