### ISSUE TITLE
Project key prefix problem

### ISSUE THREAD

**Issue by CobaltChicken** [hmvictor/radar-netbeans#52]
When projects write issues to our Sonar server (from Jenkins) the project key is prefixed with a company name and suffixed with a git branch e.g. **costcutter:ctrade-enquiry:CE-15**. The project, as viewed in my local Netbeans is just ctrade-enquiry. Result is if I use the SonarQube/Get Issues From Server, then Radar displays the list OK, but cannot tie it to the project, and hence the source.

Having selected the Sonar project, we need to be able to find or chose the project in Netbeans even if the name doesn't match. Radar should either identify the target project from the one on which the action is triggered (ideally), or in the case of finding no match to the project key, ask the user.

What I'd suggest for this action is:
1. Get the project ID from the plugin's environment.
2. Load the list of available projects from the server.
3. When displaying the popup pre-select an entry that substring-matches the project name
4. Attach the message list to the current project (maybe only if it's a substring of the selected).

**Comment by CobaltChicken** [comment]
This seems to get around my particular issue:

@@ -174,6 +175,10 @@ public class IssueLocation {
                 }
             }
         }
+        if (projectConfiguration.getKey().toString().contains(key)) {
+            return project.getProjectDirectory();  // project key is a substring of SONAR key
+        }
+

**Comment by hmvictor** [comment]
Let me analyze this case.

Thank you for your issue report.

**Comment by hmvictor** [comment]
Hi, I push some fixes for this case. There could be some issues with multi-module projects.

If you could make some test with your project it will be so helpful.

Thanks.

**Comment by dhalbert** [comment]
> Hi, I push some fixes for this case.

 Hi @hmvictor - I don't see any commits from you since May 2016. Could you try again? I'm having the same problem as the OP.

**Comment by hmvictor** [comment]
Hia @dhalbert.

Current work is in the branch 2.7: https://github.com/hmvictor/radar-netbeans/tree/Radar-2.7

Thanks.

**Comment by IlPesso** [comment]
I had a similar issue, downloaded the last snapshot 2.7 and now it works perfectly!

Thanks, it's a great plugin!!

**Comment by hmvictor** [comment]
Hi @IlPesso 

I'm glad to hear is useful to you. Thank you.
