### ISSUE TITLE
Feature request: Show issues by category

### ISSUE THREAD

**Issue by neshanjo** [hmvictor/radar-netbeans#55]
Hi,

it would be great to have the issues sorted not only by priority but also by category:

- bug
- vulnerability
- code smell
- (code duplication)

BTW: Is there a way to disable all error indicators in the source code editor window?

Kind regards
Johannes

**Comment by hmvictor** [comment]
Hi, @neshanjo 

I'm addind a feature so probably in Radar 3.0 editor annotations (error indicators) can be enabled, disabled by the user.

For the first request, let me check the SonarQube APIs.

Thanks for you feedback.

**Comment by hmvictor** [comment]
Hi, @neshanjo 

Initial support for showing issues by type is implemented in the 3.0 branch.
